steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/suresh-flask:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/suresh-flask:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute instances update-container suresh-flask-instance \
        --zone=us-central1-a \
        --container-image=gcr.io/$PROJECT_ID/suresh-flask:latest
